export const CART_ADD_ITEM = "CART_ADD_ITEM";

export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
// SAVE SHIPPING ADDRESS
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";

// SAVE SHIPPING ADDRESS
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

// DELETE CART INFO IN LOCAL STORAGE AFTER ORDER PLACED
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const Wishlist_ADD_ITEM = "Wishlist_ADD_ITEM";

export const Wishlist_REMOVE_ITEM = "Wishlist_REMOVE_ITEM";
export const Wishlist_CLEAR_ITEMS = "Wishlist_CLEAR_ITEMS";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_ERROR = "ADD_TO_WISHLIST_ERROR";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_ERROR = "REMOVE_FROM_WISHLIST_ERROR";
export const FETCH_WISHLIST_ERROR = "FETCH_WISHLIST_ERROR";
export const FETCH_WISHLIST_SUCCESS = "FETCH_WISHLIST_SUCCESS";
export const Wishlist_ADD_ITEM_FAIL = "Wishlist_ADD_ITEM_FAIL";


// PLACE ORDER
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

// RESET STATE
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

// ORDER DETAILS
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

// PAYMENT
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

// LIST OF ORDERS OF A USER
export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

// LIST OF ALL ORDERS OF ALL USERS
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

// DELIVERY STATUS OF ORDERS
export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
